[package]
name = "yes"
version = "0.1.0"
description = "yes command implemented in WebAssembly and WASI"
license = "MIT"
repository = "https://github.com/Syuparn/wasm-yes"

[[module]]
name = "yes"
source = "yes.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "yes"
module = "yes"
