name: Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: install tools for CI
      run: npm install

    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v1

    - name: build wasm
      run: npx wat2wasm yes.wat

    - name: run test
      run: npx bats test/yes.bats
